# Generated by Django 4.0 on 2021-12-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
