# Generated by Django 4.0 on 2021-12-13 12:56

from django.db import migrations, models
import stocks.models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_stock_symbol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='Tesla Inc', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=stocks.models.UppserField(max_length=6, unique=True),
        ),
    ]
